sudo: required
services:
  - docker

before_install:
  - docker build -t miki90014/docker-react -f Dockerfile.dev .

script:
  - docker run -r CI=true miki90014/docker-react npm run test

language: generic
